### ISSUE TITLE
[FEATURE] 공공데이터 활용 자전거 및 킥보드 위치 정보 저장

### ISSUE THREAD

**Issue by J-1ac** [Diving-Seagull/gandang#11]
## 기능 설명 
    공공데이터를 활용해 자전거 와 킥보드의 위치 정보를 저장하자.

## TODO
- [x] 도메인 설계
- [x] 자전거 위치 정보 테이블에 저장
- [x] 가까운 자전거 정류소 위치 찾기
- [ ] 킥보드 위치 정보 공공데이터 api 연동

**Comment by J-1ac** [comment]
킥보드 빼기로 결정
