### ISSUE TITLE
[FEATURE] 검색 관련 화면 구현

### ISSUE THREAD

**Issue by JackAhn** [Diving-Seagull/gandang#15]
## 기능 설명 
    검색 화면을 구현합니다.

## TODO
- [x] 검색 화면 디자인
- [x] 검색 결과 화면 디자인
- [x] 최근 검색 결과 출력
