### ISSUE TITLE
[FEATURE] 검색 결과 화면 구현

### ISSUE THREAD

**Issue by JackAhn** [Diving-Seagull/gandang#20]
## 기능 설명 
    검색 결과 화면 및 관련 기능들을 구현합니다.

## TODO
- [x] 검색 결과 전달
- [x] 검색 결과 출력
- [x] 검색 결과 경로 출력
- [x] 경유지 경로 출력
