### ISSUE TITLE
[FEATURE] 경로 도메인 고도화

### ISSUE THREAD

**Issue by J-1ac** [Diving-Seagull/gandang#21]
## 기능 설명 
    경로 도메인을 고도화 합시다.

## TODO
- [x] 요청객체에 start_name, end_name 추가, distance 제거
- [ ] 경로 추가 시 해안도로 네비게이션 알고리즘 적용
    - [x] 총 거리 계산해서 db에 저장
    - [x] 5m 간격으로 좌표 찍어서 list로 반환
